version: '3.8'

services:
  ansible:
    platform: linux/amd64
    hostname: ansible
    image: ftutorials/ubuntu-ansible:1.0
    container_name: ansible
    ports:
      - "2222:22"
      - "80:80"
    volumes:
      - ./config:/root/config
      - ./ssh-ansible:/root/.ssh  # Ajout du volume persistant pour la clé SSH
      - /var/run/docker.sock:/var/run/docker.sock  # Permet au conteneur Ansible d'accéder à Docker de l'hôte
    networks:
      - ansible_net

  client1:
    platform: linux/amd64
    hostname: client1
    build:
      context: ./ubuntu-ssh
    container_name: client1
    ports:
      - "2223:22"
      - "3003:3000" 
      - "8083:80" 
    networks:
      - ansible_net

  client2:
    platform: linux/amd64
    hostname: client2
    build:
      context: ./ubuntu-ssh
    container_name: client2
    ports:
      - "2224:22"
      - "3004:3000"
      - "8084:80" 
    networks:
      - ansible_net

  client3:
    platform: linux/amd64
    hostname: client3
    build:
      context: ./rocky-ssh
    container_name: client3
    ports:
      - "2225:22"
      - "3005:3000"
      - "8085:80" 
    networks:
      - ansible_net

  client4:
    platform: linux/amd64
    hostname: client4
    build:
      context: ./rocky-ssh
    container_name: client4
    ports:
      - "2226:22"
      - "3006:3000"
      - "8086:80" 
    networks:
      - ansible_net

  quiz-ansible:
    platform: linux/amd64
    image: ftutorials/quiz:ansible-4
    container_name: quiz-ansible
    ports:
      - "3000:3000"
    networks:
      - ansible_net

networks:
  ansible_net:
    driver: bridge
