# Exercice 27 : Apprendre à utiliser when pour exécuter une tâche uniquement si une condition est remplie.
# Executer le playbook apache-condition.yaml.
# Sur le serveur Ansible, créez le fichier playbook apache-condition.yaml qui doit :
# S’exécuter sur tous les hôtes.
# Installer Apache (apache2) uniquement si le système d’exploitation appartient à la famille "Debian" (ex : Debian ou Ubuntu).
# Afficher un message de confirmation après l'installation.
# Les conditions
# Effectuez les vérifications.
---
- name: Installer Apache uniquement sur Debian/Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Installer Apache2 si OS Debian/Ubuntu
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Afficher un message de confirmation
      ansible.builtin.debug:
        msg: "Apache2 a été installé sur {{ inventory_hostname }} (famille Debian)"
      when: ansible_facts['os_family'] == 'Debian'