---
# Exercice 5 : Créer un playbook qui désinstalle le package apache2.
# Consignes :
# - Créez le fichier playbook ansible apache-desinstall.yaml qui désinstalle le package apache2 à l’aide de la documentation.
# - Vérifiez si apache2 est installé.
# - Effectuez les vérifications nécessaires.
# - Exécutez le playbook ansible apache-desinstall.yaml.
#
# Ne modifiez pas la logique métier du playbook.

- name: Désinstaller Apache2 (Ubuntu)
  hosts: localhost
  become: true
  tasks:
    - name: Désinstaller le package apache2
      ansible.builtin.apt:
        name: apache2
        state: absent
        purge: true

    - name: Vérifier si apache2 est encore installé
      ansible.builtin.shell: dpkg -l | grep apache2 || true
      register: result_check
      changed_when: false

    - name: Afficher le résultat de la vérification
      ansible.builtin.debug:
        msg: >-
          {% if result_check.stdout == '' %}
            Apache2 n'est plus installé.
          {% else %}
            Apache2 est encore présent : {{ result_check.stdout }}
          {% endif %}
