---
# Exercice 4 : Créer un playbook qui installe le package apache2.
# Consignes :
# - Créez le fichier playbook ansible apache-install.yaml qui installe et démarre le service apache2 à l’aide de la documentation.
# - Vérifiez si apache2 est installé.
# - Effectuez les vérifications nécessaires.
# - Exécutez le playbook ansible apache-install.yaml.
#
# Ne modifiez pas la logique métier du playbook.

- name: Installer et démarrer Apache2 (Ubuntu)
  hosts: localhost
  become: true
  tasks:
    - name: Installer le package apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: S'assurer que le service apache2 est démarré
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
