# Exercice 26 : Créer un playbook qui met à jour un fichier de configuration Apache, puis redémarre le service Apache uniquement si ce fichier est modifié.
# Pour la réalisation de cet exercice, apache doit être installé et fonctionnel sur les clients distants de type ubuntu.
# Sur le serveur Ansible, executez le playbook et observez si le handler est déclenché.
# Sur le serveur Ansible, créez le fichier playbook apache-handler.yaml qui doit :
# - Copier un fichier index.html vers /var/www/html/index.html sur les clients distants ubuntu.
# - Utiliser le module copy avec notify pour avertir le handler si un changement est détecté.
# - Définir un handler qui redémarre le service apache2.
---
- name: Mise à jour du fichier index.html et gestion du handler Apache
  hosts: ubuntu
  become: true
  tasks:
    - name: Installer Apache2 (si besoin)
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: S'assurer que /var/www/html existe
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copier le fichier index.html
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      notify: Redémarrer apache2

  handlers:
    - name: Redémarrer apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
