---
# Exercice 9 : Copier un fichier depuis la machine de contrôle Ansible vers plusieurs machines distantes en utilisant un Playbook Ansible et le module copy.
# Documentation :
# - Sur le serveur Ansible, créez le fichier /root/sdv.conf et écrivez dedans “config de sdv”.
# - Le fichier créé devra être copié dans le répertoire /tmp des machines distantes.
# - Sur le serveur Ansible, créez le playbook ansible copie.yaml à l’aide de la documentation.
# - Sur le serveur Ansible, exécutez le playbook ansible copie.yaml
# - Vérifiez au moins sur une machine distante que le fichier a bien été copié.
#
# Ne modifiez pas la logique métier du playbook.

- name: Copier le fichier sdv.conf sur toutes les machines distantes
  hosts: all
  become: true
  tasks:
    - name: Copier le fichier sdv.conf dans /tmp
      ansible.builtin.copy:
        src: /root/config/sdv.conf
        dest: /tmp/sdv.conf
        owner: root
        group: root
        mode: '0644'
