---
# Exercice 18 : Adapter le playbook pour copier un fichier depuis la machine de contrôle vers tous les clients distants, en utilisant des variables pour rendre le script réutilisable.
# Consignes :
# - Utilisez des variables pour le chemin source (src), le chemin de destination (dest), le propriétaire (owner), le groupe (group) et les permissions (mode).
# - Le playbook doit permettre de copier n'importe quel fichier en adaptant simplement les variables.
#
# Ne modifiez pas la logique métier du playbook.

- name: Copier le fichier sdv.conf sur toutes les machines distantes
  hosts: all
  become: true
  tasks:
    - name: Copier le fichier sdv.conf dans /tmp
      ansible.builtin.copy:
        src: /root/config/sdv.conf
        dest: /tmp/sdv.conf
        owner: root
        group: root
        mode: '0644'
